image: Visual Studio 2015  # образ для сборки

environment:
  nodejs_version: "6"
  MYSQL_DATABASE: node_mysql
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  MYSQL_PORT: 3306
  DOCKER_USERNAME: murrk
  DOCKER_PASSWORD:
    secure: l6Nlva10IqJeiLSCqbulog==
  DOCKER_REGISTRY: docker.io/murrk/

services:
  - mysql

branches:
  only:
    - master  

build: off 

install:
  - ps: npm install -g npm@latest
  - docker version
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./app-shop.jar -P:jdbc.url=jdbc:mysql://192.168.99.100:3306/app -P:jdbc.user=app -P:jdbc.password=pass" -PassThru


build_script:
  - ps: docker-compose -f docker-compose-mysql.yml up -d build
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)
  
deploy_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose -f docker-compose-mysql.yml up -d push
  
on_finish:
  - ps: Stop-Process -Id $App.Id  
